package org.arunm;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Arun.Menon' at '3/28/17 9:03 AM' with Gradle 2.11
 *
 * @author Arun.Menon, @date 3/28/17 9:03 AM
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		assertTrue(true);
	}
}
